default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['USERNAME'] %>
  password: Panther20zss
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: sweetgems_development

test:
  <<: *default
  database: sweetgems_test

production:
  <<: *default
  database: sweetgems_production
